#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("select_V", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("s0_axis_video_TDATA", 8, hls_in, 1, "axis", "in_data", 1),
	Port_Property("s0_axis_video_TVALID", 1, hls_in, 7, "axis", "in_vld", 1),
	Port_Property("s0_axis_video_TREADY", 1, hls_out, 7, "axis", "in_acc", 1),
	Port_Property("s0_axis_video_TKEEP", 1, hls_in, 2, "axis", "in_data", 1),
	Port_Property("s0_axis_video_TSTRB", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("s0_axis_video_TUSER", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("s0_axis_video_TLAST", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("s0_axis_video_TID", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("s0_axis_video_TDEST", 1, hls_in, 7, "axis", "in_data", 1),
	Port_Property("s1_axis_video_TDATA", 8, hls_in, 8, "axis", "in_data", 1),
	Port_Property("s1_axis_video_TVALID", 1, hls_in, 14, "axis", "in_vld", 1),
	Port_Property("s1_axis_video_TREADY", 1, hls_out, 14, "axis", "in_acc", 1),
	Port_Property("s1_axis_video_TKEEP", 1, hls_in, 9, "axis", "in_data", 1),
	Port_Property("s1_axis_video_TSTRB", 1, hls_in, 10, "axis", "in_data", 1),
	Port_Property("s1_axis_video_TUSER", 1, hls_in, 11, "axis", "in_data", 1),
	Port_Property("s1_axis_video_TLAST", 1, hls_in, 12, "axis", "in_data", 1),
	Port_Property("s1_axis_video_TID", 1, hls_in, 13, "axis", "in_data", 1),
	Port_Property("s1_axis_video_TDEST", 1, hls_in, 14, "axis", "in_data", 1),
	Port_Property("m_axis_video_TDATA", 8, hls_out, 15, "axis", "out_data", 1),
	Port_Property("m_axis_video_TVALID", 1, hls_out, 21, "axis", "out_vld", 1),
	Port_Property("m_axis_video_TREADY", 1, hls_in, 21, "axis", "out_acc", 1),
	Port_Property("m_axis_video_TKEEP", 1, hls_out, 16, "axis", "out_data", 1),
	Port_Property("m_axis_video_TSTRB", 1, hls_out, 17, "axis", "out_data", 1),
	Port_Property("m_axis_video_TUSER", 1, hls_out, 18, "axis", "out_data", 1),
	Port_Property("m_axis_video_TLAST", 1, hls_out, 19, "axis", "out_data", 1),
	Port_Property("m_axis_video_TID", 1, hls_out, 20, "axis", "out_data", 1),
	Port_Property("m_axis_video_TDEST", 1, hls_out, 21, "axis", "out_data", 1),
	Port_Property("hsize_in", 32, hls_in, 22, "ap_none", "in_data", 1),
	Port_Property("vsize_in", 32, hls_in, 23, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "switch_axis";
