// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _image_filter_HH_
#define _image_filter_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Block_proc.h"
#include "AXIvideo2Mat.h"
#include "GaussianBlur.h"
#include "Duplicate183.h"
#include "Duplicate.h"
#include "MinMaxLoc.h"
#include "CmpS.h"
#include "PaintMask.h"
#include "Mat2AXIvideo.h"
#include "Block_proc222.h"
#include "fifo_w10_d2_A.h"
#include "fifo_w11_d2_A.h"
#include "fifo_w8_d2_A.h"
#include "start_for_GaussiaHfu.h"
#include "start_for_DuplicaIfE.h"
#include "start_for_DuplicaJfO.h"
#include "start_for_MinMaxLKfY.h"
#include "start_for_PaintMaLf8.h"
#include "start_for_Mat2AXIMgi.h"
#include "image_filter_CONTROL_BUS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32>
struct image_filter : public sc_module {
    // Port declarations 41
    sc_in< sc_logic > s_axi_CONTROL_BUS_AWVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_AWADDR;
    sc_in< sc_logic > s_axi_CONTROL_BUS_WVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_WREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_WDATA;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH/8> > s_axi_CONTROL_BUS_WSTRB;
    sc_in< sc_logic > s_axi_CONTROL_BUS_ARVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_ARADDR;
    sc_out< sc_logic > s_axi_CONTROL_BUS_RVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_RREADY;
    sc_out< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_RDATA;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_RRESP;
    sc_out< sc_logic > s_axi_CONTROL_BUS_BVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_BREADY;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<24> > video_in_TDATA;
    sc_in< sc_lv<3> > video_in_TKEEP;
    sc_in< sc_lv<3> > video_in_TSTRB;
    sc_in< sc_lv<1> > video_in_TUSER;
    sc_in< sc_lv<1> > video_in_TLAST;
    sc_in< sc_lv<1> > video_in_TID;
    sc_in< sc_lv<1> > video_in_TDEST;
    sc_out< sc_lv<24> > video_out_TDATA;
    sc_out< sc_lv<3> > video_out_TKEEP;
    sc_out< sc_lv<3> > video_out_TSTRB;
    sc_out< sc_lv<1> > video_out_TUSER;
    sc_out< sc_lv<1> > video_out_TLAST;
    sc_out< sc_lv<1> > video_out_TID;
    sc_out< sc_lv<1> > video_out_TDEST;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > video_in_TVALID;
    sc_out< sc_logic > video_in_TREADY;
    sc_out< sc_logic > video_out_TVALID;
    sc_in< sc_logic > video_out_TREADY;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    image_filter(sc_module_name name);
    SC_HAS_PROCESS(image_filter);

    ~image_filter();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    image_filter_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>* image_filter_CONTROL_BUS_s_axi_U;
    Block_proc* Block_proc_U0;
    AXIvideo2Mat* AXIvideo2Mat_U0;
    GaussianBlur* GaussianBlur_U0;
    Duplicate183* Duplicate183_U0;
    Duplicate* Duplicate_U0;
    MinMaxLoc* MinMaxLoc_U0;
    CmpS* CmpS_U0;
    PaintMask* PaintMask_U0;
    Mat2AXIvideo* Mat2AXIvideo_U0;
    Block_proc222* Block_proc222_U0;
    fifo_w10_d2_A* img_in_rows_V_c_U;
    fifo_w11_d2_A* img_in_cols_V_c_U;
    fifo_w8_d2_A* img_in_data_stream_0_U;
    fifo_w8_d2_A* img_in_data_stream_1_U;
    fifo_w8_d2_A* img_in_data_stream_2_U;
    fifo_w10_d2_A* img_in_rows_V_c19_U;
    fifo_w11_d2_A* img_in_cols_V_c20_U;
    fifo_w8_d2_A* img_0_data_stream_0_U;
    fifo_w8_d2_A* img_0_data_stream_1_U;
    fifo_w8_d2_A* img_0_data_stream_2_U;
    fifo_w8_d2_A* img_1_data_stream_0_U;
    fifo_w8_d2_A* img_1_data_stream_1_U;
    fifo_w8_d2_A* img_1_data_stream_2_U;
    fifo_w8_d2_A* img_in2_data_stream_s_U;
    fifo_w8_d2_A* img_in2_data_stream_1_U;
    fifo_w8_d2_A* img_in2_data_stream_2_U;
    fifo_w8_d2_A* img_2_data_stream_0_U;
    fifo_w8_d2_A* img_2_data_stream_1_U;
    fifo_w8_d2_A* img_2_data_stream_2_U;
    fifo_w8_d2_A* img_3_data_stream_0_U;
    fifo_w8_d2_A* img_3_data_stream_1_U;
    fifo_w8_d2_A* img_3_data_stream_2_U;
    fifo_w8_d2_A* max_U;
    fifo_w8_d2_A* mask_data_stream_0_s_U;
    fifo_w8_d2_A* img_out_data_stream_s_U;
    fifo_w8_d2_A* img_out_data_stream_1_U;
    fifo_w8_d2_A* img_out_data_stream_2_U;
    start_for_GaussiaHfu* start_for_GaussiaHfu_U;
    start_for_DuplicaIfE* start_for_DuplicaIfE_U;
    start_for_DuplicaJfO* start_for_DuplicaJfO_U;
    start_for_MinMaxLKfY* start_for_MinMaxLKfY_U;
    start_for_PaintMaLf8* start_for_PaintMaLf8_U;
    start_for_Mat2AXIMgi* start_for_Mat2AXIMgi_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > Block_proc_U0_ap_start;
    sc_signal< sc_logic > Block_proc_U0_ap_done;
    sc_signal< sc_logic > Block_proc_U0_ap_continue;
    sc_signal< sc_logic > Block_proc_U0_ap_idle;
    sc_signal< sc_logic > Block_proc_U0_ap_ready;
    sc_signal< sc_lv<10> > Block_proc_U0_img_in_rows_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_img_in_rows_V_out_write;
    sc_signal< sc_lv<11> > Block_proc_U0_img_in_cols_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_img_in_cols_V_out_write;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_start;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_done;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_continue;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_idle;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_out;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_write;
    sc_signal< sc_logic > AXIvideo2Mat_U0_video_in_TREADY;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_rows_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_cols_V_read;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_0_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_0_V_write;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_1_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_1_V_write;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_2_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_2_V_write;
    sc_signal< sc_lv<10> > AXIvideo2Mat_U0_img_rows_V_out_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_rows_V_out_write;
    sc_signal< sc_lv<11> > AXIvideo2Mat_U0_img_cols_V_out_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_cols_V_out_write;
    sc_signal< sc_logic > GaussianBlur_U0_ap_start;
    sc_signal< sc_logic > GaussianBlur_U0_ap_done;
    sc_signal< sc_logic > GaussianBlur_U0_ap_continue;
    sc_signal< sc_logic > GaussianBlur_U0_ap_idle;
    sc_signal< sc_logic > GaussianBlur_U0_ap_ready;
    sc_signal< sc_logic > GaussianBlur_U0_start_out;
    sc_signal< sc_logic > GaussianBlur_U0_start_write;
    sc_signal< sc_logic > GaussianBlur_U0_p_src_rows_V_read;
    sc_signal< sc_logic > GaussianBlur_U0_p_src_cols_V_read;
    sc_signal< sc_logic > GaussianBlur_U0_p_src_data_stream_0_V_read;
    sc_signal< sc_logic > GaussianBlur_U0_p_src_data_stream_1_V_read;
    sc_signal< sc_logic > GaussianBlur_U0_p_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > GaussianBlur_U0_p_dst_data_stream_0_V_din;
    sc_signal< sc_logic > GaussianBlur_U0_p_dst_data_stream_0_V_write;
    sc_signal< sc_lv<8> > GaussianBlur_U0_p_dst_data_stream_1_V_din;
    sc_signal< sc_logic > GaussianBlur_U0_p_dst_data_stream_1_V_write;
    sc_signal< sc_lv<8> > GaussianBlur_U0_p_dst_data_stream_2_V_din;
    sc_signal< sc_logic > GaussianBlur_U0_p_dst_data_stream_2_V_write;
    sc_signal< sc_logic > Duplicate183_U0_ap_start;
    sc_signal< sc_logic > Duplicate183_U0_start_full_n;
    sc_signal< sc_logic > Duplicate183_U0_ap_done;
    sc_signal< sc_logic > Duplicate183_U0_ap_continue;
    sc_signal< sc_logic > Duplicate183_U0_ap_idle;
    sc_signal< sc_logic > Duplicate183_U0_ap_ready;
    sc_signal< sc_logic > Duplicate183_U0_start_out;
    sc_signal< sc_logic > Duplicate183_U0_start_write;
    sc_signal< sc_logic > Duplicate183_U0_src_data_stream_V_read;
    sc_signal< sc_logic > Duplicate183_U0_src_data_stream_V1_read;
    sc_signal< sc_logic > Duplicate183_U0_src_data_stream_V2_read;
    sc_signal< sc_lv<8> > Duplicate183_U0_dst1_data_stream_V_din;
    sc_signal< sc_logic > Duplicate183_U0_dst1_data_stream_V_write;
    sc_signal< sc_lv<8> > Duplicate183_U0_dst1_data_stream_V3_din;
    sc_signal< sc_logic > Duplicate183_U0_dst1_data_stream_V3_write;
    sc_signal< sc_lv<8> > Duplicate183_U0_dst1_data_stream_V4_din;
    sc_signal< sc_logic > Duplicate183_U0_dst1_data_stream_V4_write;
    sc_signal< sc_lv<8> > Duplicate183_U0_dst2_data_stream_V_din;
    sc_signal< sc_logic > Duplicate183_U0_dst2_data_stream_V_write;
    sc_signal< sc_lv<8> > Duplicate183_U0_dst2_data_stream_V5_din;
    sc_signal< sc_logic > Duplicate183_U0_dst2_data_stream_V5_write;
    sc_signal< sc_lv<8> > Duplicate183_U0_dst2_data_stream_V6_din;
    sc_signal< sc_logic > Duplicate183_U0_dst2_data_stream_V6_write;
    sc_signal< sc_logic > Duplicate_U0_ap_start;
    sc_signal< sc_logic > Duplicate_U0_ap_done;
    sc_signal< sc_logic > Duplicate_U0_ap_continue;
    sc_signal< sc_logic > Duplicate_U0_ap_idle;
    sc_signal< sc_logic > Duplicate_U0_ap_ready;
    sc_signal< sc_logic > Duplicate_U0_start_out;
    sc_signal< sc_logic > Duplicate_U0_start_write;
    sc_signal< sc_logic > Duplicate_U0_src_data_stream_0_V_read;
    sc_signal< sc_logic > Duplicate_U0_src_data_stream_1_V_read;
    sc_signal< sc_logic > Duplicate_U0_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > Duplicate_U0_dst1_data_stream_0_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst1_data_stream_0_V_write;
    sc_signal< sc_lv<8> > Duplicate_U0_dst1_data_stream_1_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst1_data_stream_1_V_write;
    sc_signal< sc_lv<8> > Duplicate_U0_dst1_data_stream_2_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst1_data_stream_2_V_write;
    sc_signal< sc_lv<8> > Duplicate_U0_dst2_data_stream_0_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst2_data_stream_0_V_write;
    sc_signal< sc_lv<8> > Duplicate_U0_dst2_data_stream_1_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst2_data_stream_1_V_write;
    sc_signal< sc_lv<8> > Duplicate_U0_dst2_data_stream_2_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst2_data_stream_2_V_write;
    sc_signal< sc_logic > MinMaxLoc_U0_ap_start;
    sc_signal< sc_logic > MinMaxLoc_U0_ap_done;
    sc_signal< sc_logic > MinMaxLoc_U0_ap_continue;
    sc_signal< sc_logic > MinMaxLoc_U0_ap_idle;
    sc_signal< sc_logic > MinMaxLoc_U0_ap_ready;
    sc_signal< sc_logic > MinMaxLoc_U0_src_data_stream_0_V_read;
    sc_signal< sc_logic > MinMaxLoc_U0_src_data_stream_1_V_read;
    sc_signal< sc_logic > MinMaxLoc_U0_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > MinMaxLoc_U0_ap_return;
    sc_signal< sc_logic > ap_channel_done_max;
    sc_signal< sc_logic > max_full_n;
    sc_signal< sc_logic > CmpS_U0_ap_start;
    sc_signal< sc_logic > CmpS_U0_ap_done;
    sc_signal< sc_logic > CmpS_U0_ap_continue;
    sc_signal< sc_logic > CmpS_U0_ap_idle;
    sc_signal< sc_logic > CmpS_U0_ap_ready;
    sc_signal< sc_logic > CmpS_U0_src_data_stream_0_V_read;
    sc_signal< sc_logic > CmpS_U0_src_data_stream_1_V_read;
    sc_signal< sc_logic > CmpS_U0_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > CmpS_U0_dst_data_stream_V_din;
    sc_signal< sc_logic > CmpS_U0_dst_data_stream_V_write;
    sc_signal< sc_logic > PaintMask_U0_ap_start;
    sc_signal< sc_logic > PaintMask_U0_ap_done;
    sc_signal< sc_logic > PaintMask_U0_ap_continue;
    sc_signal< sc_logic > PaintMask_U0_ap_idle;
    sc_signal< sc_logic > PaintMask_U0_ap_ready;
    sc_signal< sc_logic > PaintMask_U0_start_out;
    sc_signal< sc_logic > PaintMask_U0_start_write;
    sc_signal< sc_logic > PaintMask_U0_p_src_data_stream_0_V_read;
    sc_signal< sc_logic > PaintMask_U0_p_src_data_stream_1_V_read;
    sc_signal< sc_logic > PaintMask_U0_p_src_data_stream_2_V_read;
    sc_signal< sc_logic > PaintMask_U0_p_mask_data_stream_V_read;
    sc_signal< sc_lv<8> > PaintMask_U0_p_dst_data_stream_0_V_din;
    sc_signal< sc_logic > PaintMask_U0_p_dst_data_stream_0_V_write;
    sc_signal< sc_lv<8> > PaintMask_U0_p_dst_data_stream_1_V_din;
    sc_signal< sc_logic > PaintMask_U0_p_dst_data_stream_1_V_write;
    sc_signal< sc_lv<8> > PaintMask_U0_p_dst_data_stream_2_V_din;
    sc_signal< sc_logic > PaintMask_U0_p_dst_data_stream_2_V_write;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_start;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_done;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_continue;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_idle;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_ready;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_0_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_1_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_2_V_read;
    sc_signal< sc_lv<24> > Mat2AXIvideo_U0_video_out_TDATA;
    sc_signal< sc_logic > Mat2AXIvideo_U0_video_out_TVALID;
    sc_signal< sc_lv<3> > Mat2AXIvideo_U0_video_out_TKEEP;
    sc_signal< sc_lv<3> > Mat2AXIvideo_U0_video_out_TSTRB;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_video_out_TUSER;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_video_out_TLAST;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_video_out_TID;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_video_out_TDEST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > Block_proc222_U0_ap_start;
    sc_signal< sc_logic > Block_proc222_U0_ap_done;
    sc_signal< sc_logic > Block_proc222_U0_ap_continue;
    sc_signal< sc_logic > Block_proc222_U0_ap_idle;
    sc_signal< sc_logic > Block_proc222_U0_ap_ready;
    sc_signal< sc_lv<32> > Block_proc222_U0_x;
    sc_signal< sc_logic > Block_proc222_U0_x_ap_vld;
    sc_signal< sc_lv<32> > Block_proc222_U0_y;
    sc_signal< sc_logic > Block_proc222_U0_y_ap_vld;
    sc_signal< sc_logic > img_in_rows_V_c_full_n;
    sc_signal< sc_lv<10> > img_in_rows_V_c_dout;
    sc_signal< sc_logic > img_in_rows_V_c_empty_n;
    sc_signal< sc_logic > img_in_cols_V_c_full_n;
    sc_signal< sc_lv<11> > img_in_cols_V_c_dout;
    sc_signal< sc_logic > img_in_cols_V_c_empty_n;
    sc_signal< sc_logic > img_in_data_stream_0_full_n;
    sc_signal< sc_lv<8> > img_in_data_stream_0_dout;
    sc_signal< sc_logic > img_in_data_stream_0_empty_n;
    sc_signal< sc_logic > img_in_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_in_data_stream_1_dout;
    sc_signal< sc_logic > img_in_data_stream_1_empty_n;
    sc_signal< sc_logic > img_in_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_in_data_stream_2_dout;
    sc_signal< sc_logic > img_in_data_stream_2_empty_n;
    sc_signal< sc_logic > img_in_rows_V_c19_full_n;
    sc_signal< sc_lv<10> > img_in_rows_V_c19_dout;
    sc_signal< sc_logic > img_in_rows_V_c19_empty_n;
    sc_signal< sc_logic > img_in_cols_V_c20_full_n;
    sc_signal< sc_lv<11> > img_in_cols_V_c20_dout;
    sc_signal< sc_logic > img_in_cols_V_c20_empty_n;
    sc_signal< sc_logic > img_0_data_stream_0_full_n;
    sc_signal< sc_lv<8> > img_0_data_stream_0_dout;
    sc_signal< sc_logic > img_0_data_stream_0_empty_n;
    sc_signal< sc_logic > img_0_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_0_data_stream_1_dout;
    sc_signal< sc_logic > img_0_data_stream_1_empty_n;
    sc_signal< sc_logic > img_0_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_0_data_stream_2_dout;
    sc_signal< sc_logic > img_0_data_stream_2_empty_n;
    sc_signal< sc_logic > img_1_data_stream_0_full_n;
    sc_signal< sc_lv<8> > img_1_data_stream_0_dout;
    sc_signal< sc_logic > img_1_data_stream_0_empty_n;
    sc_signal< sc_logic > img_1_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_1_data_stream_1_dout;
    sc_signal< sc_logic > img_1_data_stream_1_empty_n;
    sc_signal< sc_logic > img_1_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_1_data_stream_2_dout;
    sc_signal< sc_logic > img_1_data_stream_2_empty_n;
    sc_signal< sc_logic > img_in2_data_stream_s_full_n;
    sc_signal< sc_lv<8> > img_in2_data_stream_s_dout;
    sc_signal< sc_logic > img_in2_data_stream_s_empty_n;
    sc_signal< sc_logic > img_in2_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_in2_data_stream_1_dout;
    sc_signal< sc_logic > img_in2_data_stream_1_empty_n;
    sc_signal< sc_logic > img_in2_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_in2_data_stream_2_dout;
    sc_signal< sc_logic > img_in2_data_stream_2_empty_n;
    sc_signal< sc_logic > img_2_data_stream_0_full_n;
    sc_signal< sc_lv<8> > img_2_data_stream_0_dout;
    sc_signal< sc_logic > img_2_data_stream_0_empty_n;
    sc_signal< sc_logic > img_2_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_2_data_stream_1_dout;
    sc_signal< sc_logic > img_2_data_stream_1_empty_n;
    sc_signal< sc_logic > img_2_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_2_data_stream_2_dout;
    sc_signal< sc_logic > img_2_data_stream_2_empty_n;
    sc_signal< sc_logic > img_3_data_stream_0_full_n;
    sc_signal< sc_lv<8> > img_3_data_stream_0_dout;
    sc_signal< sc_logic > img_3_data_stream_0_empty_n;
    sc_signal< sc_logic > img_3_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_3_data_stream_1_dout;
    sc_signal< sc_logic > img_3_data_stream_1_empty_n;
    sc_signal< sc_logic > img_3_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_3_data_stream_2_dout;
    sc_signal< sc_logic > img_3_data_stream_2_empty_n;
    sc_signal< sc_lv<8> > max_dout;
    sc_signal< sc_logic > max_empty_n;
    sc_signal< sc_logic > mask_data_stream_0_s_full_n;
    sc_signal< sc_lv<8> > mask_data_stream_0_s_dout;
    sc_signal< sc_logic > mask_data_stream_0_s_empty_n;
    sc_signal< sc_logic > img_out_data_stream_s_full_n;
    sc_signal< sc_lv<8> > img_out_data_stream_s_dout;
    sc_signal< sc_logic > img_out_data_stream_s_empty_n;
    sc_signal< sc_logic > img_out_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_out_data_stream_1_dout;
    sc_signal< sc_logic > img_out_data_stream_1_empty_n;
    sc_signal< sc_logic > img_out_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_out_data_stream_2_dout;
    sc_signal< sc_logic > img_out_data_stream_2_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_Block_proc_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Block_proc_U0_ap_ready;
    sc_signal< sc_lv<2> > Block_proc_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_lv<2> > AXIvideo2Mat_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_Block_proc222_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Block_proc222_U0_ap_ready;
    sc_signal< sc_lv<2> > Block_proc222_U0_ap_ready_count;
    sc_signal< sc_logic > Block_proc_U0_start_full_n;
    sc_signal< sc_logic > Block_proc_U0_start_write;
    sc_signal< sc_lv<1> > start_for_GaussianBlur_U0_din;
    sc_signal< sc_logic > start_for_GaussianBlur_U0_full_n;
    sc_signal< sc_lv<1> > start_for_GaussianBlur_U0_dout;
    sc_signal< sc_logic > start_for_GaussianBlur_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Duplicate183_U0_din;
    sc_signal< sc_logic > start_for_Duplicate183_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Duplicate183_U0_dout;
    sc_signal< sc_logic > start_for_Duplicate183_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Duplicate_U0_din;
    sc_signal< sc_logic > start_for_Duplicate_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Duplicate_U0_dout;
    sc_signal< sc_logic > start_for_Duplicate_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_MinMaxLoc_U0_din;
    sc_signal< sc_logic > start_for_MinMaxLoc_U0_full_n;
    sc_signal< sc_lv<1> > start_for_MinMaxLoc_U0_dout;
    sc_signal< sc_logic > start_for_MinMaxLoc_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_PaintMask_U0_din;
    sc_signal< sc_logic > start_for_PaintMask_U0_full_n;
    sc_signal< sc_lv<1> > start_for_PaintMask_U0_dout;
    sc_signal< sc_logic > start_for_PaintMask_U0_empty_n;
    sc_signal< sc_logic > MinMaxLoc_U0_start_full_n;
    sc_signal< sc_logic > MinMaxLoc_U0_start_write;
    sc_signal< sc_logic > CmpS_U0_start_full_n;
    sc_signal< sc_logic > CmpS_U0_start_write;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_din;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_dout;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_empty_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_full_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_write;
    sc_signal< sc_logic > Block_proc222_U0_start_full_n;
    sc_signal< sc_logic > Block_proc222_U0_start_write;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_S_AXI_WSTRB_WIDTH;
    static const int C_S_AXI_ADDR_WIDTH;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_AXIvideo2Mat_U0_ap_continue();
    void thread_AXIvideo2Mat_U0_ap_start();
    void thread_Block_proc222_U0_ap_continue();
    void thread_Block_proc222_U0_ap_start();
    void thread_Block_proc222_U0_start_full_n();
    void thread_Block_proc222_U0_start_write();
    void thread_Block_proc_U0_ap_continue();
    void thread_Block_proc_U0_ap_start();
    void thread_Block_proc_U0_start_full_n();
    void thread_Block_proc_U0_start_write();
    void thread_CmpS_U0_ap_continue();
    void thread_CmpS_U0_ap_start();
    void thread_CmpS_U0_start_full_n();
    void thread_CmpS_U0_start_write();
    void thread_Duplicate183_U0_ap_continue();
    void thread_Duplicate183_U0_ap_start();
    void thread_Duplicate183_U0_start_full_n();
    void thread_Duplicate_U0_ap_continue();
    void thread_Duplicate_U0_ap_start();
    void thread_GaussianBlur_U0_ap_continue();
    void thread_GaussianBlur_U0_ap_start();
    void thread_Mat2AXIvideo_U0_ap_continue();
    void thread_Mat2AXIvideo_U0_ap_start();
    void thread_Mat2AXIvideo_U0_start_full_n();
    void thread_Mat2AXIvideo_U0_start_write();
    void thread_MinMaxLoc_U0_ap_continue();
    void thread_MinMaxLoc_U0_ap_start();
    void thread_MinMaxLoc_U0_start_full_n();
    void thread_MinMaxLoc_U0_start_write();
    void thread_PaintMask_U0_ap_continue();
    void thread_PaintMask_U0_ap_start();
    void thread_ap_channel_done_max();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_AXIvideo2Mat_U0_ap_ready();
    void thread_ap_sync_Block_proc222_U0_ap_ready();
    void thread_ap_sync_Block_proc_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_start_for_Duplicate183_U0_din();
    void thread_start_for_Duplicate_U0_din();
    void thread_start_for_GaussianBlur_U0_din();
    void thread_start_for_Mat2AXIvideo_U0_din();
    void thread_start_for_MinMaxLoc_U0_din();
    void thread_start_for_PaintMask_U0_din();
    void thread_video_in_TREADY();
    void thread_video_out_TDATA();
    void thread_video_out_TDEST();
    void thread_video_out_TID();
    void thread_video_out_TKEEP();
    void thread_video_out_TLAST();
    void thread_video_out_TSTRB();
    void thread_video_out_TUSER();
    void thread_video_out_TVALID();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
